security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        nim_admin_user:
            id: fos_user.user_provider.username
        nim_api_user:
            memory:
                users:
                    api: { password: %nim_api_password%, roles: 'ROLE_API' }

    firewalls:
        admin:
            pattern: ^/admin
            form_login:
                provider: nim_admin_user
                csrf_provider: form.csrf_provider
                login_path:          /admin/login
                check_path:          /admin/login_check
                failure_path:        /admin/login
                default_target_path: /admin/dashboard
            logout:
                path:   /admin/logout
                target: /admin/login
            anonymous:    true
        api:
            pattern: ^/api
            http_basic: ~
            provider: nim_api_user
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/admin/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/assets/compiled, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: ROLE_API }
        - { path: ^/admin, role: ROLE_SUPER_ADMIN }
